### ISSUE TITLE
Re-export smol crate?

### ISSUE THREAD

**Issue by wusyong** [wusyong/smol-potat#5]
This crate re-exported the smol crate starting with v0.3.2. It's convenience approach to do it but I feel like maybe someone would have different opinion. Any feedback is welcomed!

**Comment by danieleades** [comment]
I don't think it should be re-exported.

I think this crate should be tightly scoped to *only* export the proc macros. If users want access to the smol API they should import it in their own crate.

Right now you're exporting a bunch of smol types. I think that makes the relationship between smol and smol-potat confusing. Is it a fork? Or a compat layer?

I think the best way to see uptake of this library is to present it as a tiny utility library, which adds to smol, instead of competing with it.

**Comment by wusyong** [comment]
Yeah, I think you are right. This probably will confuse the users. I do treat this macro as a smol utility. I will revert it back to re-export run function only in next version.

**Comment by wusyong** [comment]
It's now reverted it back on [`93c5be1`](https://github.com/wusyong/smol-potat/commit/93c5be158e38dbb3e19a74a483db4367065f37ec)
